ARG KIWIX_TOOLS_VERSION=latest
FROM ghcr.io/laikulo/kiwix-tools:${KIWIX_TOOLS_VERSION}
ADD --chmod=755 --chown=0:0 entrypoint /usr/local/bin/entrypoint
RUN useradd -m kiwix -u 1000
USER kiwix
WORKDIR /home/kiwix
EXPOSE 8080
ENTRYPOINT [ "/usr/local/bin/entrypoint" ]
